spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=ThisIsASecretKeyThatIsAtLeast32CharactersLong!!
jwt.expiration=3600000
