# ---- JPA / Hibernate ----
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ---- PostgreSQL Driver ----
spring.datasource.driver-class-name=org.postgresql.Driver